CREATE TRIGGER TRD_VENT_PRODUCTOS
    ON VENT_PRODUCTOS
    AFTER DELETE
AS
BEGIN
    INSERT INTO VENT_PRODUCTOS_LOG(ID_PRO, NOMBRE_PRO, DESCRIPCION_PRO, PRECIO_PRO, ELIMINADO_PRO, FECHA_PRO, FECHA_PRO_LOG, UDI_LOG)
    SELECT ID_PRO, NOMBRE_PRO, DESCRIPCION_PRO, PRECIO_PRO, ELIMINADO_PRO, FECHA_PRO, GETDATE(), 'D'
    FROM deleted;
END
go

