CREATE TRIGGER TRI_GEN_CLIENTES
    ON GEN_CLIENTES
    AFTER INSERT
AS
BEGIN
    INSERT INTO GEN_CLIENTES_LOG(ID_CLI, NOMBRE_CLI, CIUDAD_CLI, FECHA_CLI, ELIMINADO_CLI, FECHA_CLI_LOG, UDI_LOG)
    SELECT ID_CLI, NOMBRE_CLI, CIUDAD_CLI, FECHA_CLI, ELIMINADO_CLI, GETDATE(), 'I'
    FROM inserted;
END;
go

