CREATE TRIGGER TRI_VENT_PRODUCTOS
    ON VENT_PRODUCTOS
    AFTER INSERT
AS
BEGIN
    INSERT INTO VENT_PRODUCTOS_LOG(ID_PRO, NOMBRE_PRO, DESCRIPCION_PRO, PRECIO_PRO, ELIMINADO_PRO, FECHA_PRO, FECHA_PRO_LOG, UDI_LOG)
    SELECT ID_PRO, NOMBRE_PRO, DESCRIPCION_PRO, PRECIO_PRO, ELIMINADO_PRO, FECHA_PRO, GETDATE(), 'I'
    FROM inserted;
END
go

