CREATE TRIGGER TRU_GEN_CLIENTES
    ON GEN_CLIENTES
    AFTER UPDATE
AS
    BEGIN
        INSERT INTO GEN_CLIENTES_LOG(ID_CLI, NOMBRE_CLI, CIUDAD_CLI, FECHA_CLI, ELIMINADO_CLI, FECHA_CLI_LOG, UDI_LOG)
        SELECT ID_CLI, NOMBRE_CLI, CIUDAD_CLI, FECHA_CLI, ELIMINADO_CLI, GETDATE(), 'U'
        FROM inserted;
    END;
go

